#!/bin/sh

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR
cat <<EOF > liboathtest.c
#include <oath.h>

int main(void)
{
  if (!oath_check_version (OATH_VERSION))
    return 1;

  return 0;
}
EOF

gcc -o liboathtest liboathtest.c `pkg-config --cflags --libs liboath`
echo "PASS: gcc"
[ -x liboathtest ]
./liboathtest
echo "PASS: run"
man -P cat oathtool
man -P cat oath_init
echo "PASS: man"
oathtool --version
oathtool --help
oathtool --version | head -1 | (! grep -v '(OATH Toolkit)')
echo "PASS: oathtool liboath version"
